name: Run updateindex.js on gh-pages

on:
  push:
    branches:
      - gh-pages

jobs:
  run-update-script:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 23.11.0
        uses: actions/setup-node@v3
        with:
          node-version: '23.11.0'

      - name: Check Node.js version
        run: node -v

      - name: Run updateindex.js
        run: node updateindex.js
