name: Generate Index HTML

on:
  pull_request:
    branches:
      - gh-branch

jobs:
  generate-index:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Find folders with .html files and generate an index.html file
      - name: Generate index.html
        run: |
          # Find all folders in the root with .html files
          folders=$(find . -type f -name "*.html" -exec dirname {} \; | sort -u | grep -v "^\.$")
          
          # Generate index.html content
          echo "<!DOCTYPE html>" > index.html
          echo "<html>" >> index.html
          echo "<head><title>Index</title></head>" >> index.html
          echo "<body>" >> index.html
          echo "<h1>Index of Folders with HTML Files</h1>" >> index.html
          echo "<ul>" >> index.html
          for folder in $folders; do
            folder_name=$(basename $folder)
            echo "<li><a href='$folder_name/'>$folder_name</a></li>" >> index.html
          done
          echo "</ul>" >> index.html
          echo "</body>" >> index.html
          echo "</html>" >> index.html

      # Step 3: Commit and push the index.html file (optional for pull requests)
      - name: Commit and push changes
        if: github.event_name == 'pull_request'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Generate index.html for PR"
          git push
