name: Generate and Deploy index.html

# Trigger this workflow when anything changes inside the combined-reports folder
on:
  push:
    paths:
      - 'combined-reports/**'

jobs:
  generate-report: # First job: create the HTML index
    runs-on: self-hosted # You can change to ubuntu-latest if you don't use a self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Checkout the code from the repo

      - name: Prepare Testapp directory and generate index.html
        run: |
        # Create output structure and copy reports into Testapp/
          mkdir -p Testapp/combined-reports
          cp -r combined-reports/* Testapp/combined-reports/

        # Navigate to the folder where HTML index will be generated
          cd Testapp/combined-reports

        # Start building the HTML index
          echo "<!DOCTYPE html>" > index.html
          echo "<html><head><title>All Reports</title></head><body>" >> index.html
          echo "<h1>All Reports</h1>" >> index.html

        # Add folder links (only folders inside combined-reports)
          echo "<h2>Folders</h2>" >> index.html
          for folder in */; do
            foldername=$(basename "$folder")
            echo "<a href='$folder'>$foldername/</a><br>" >> index.html
          done

        # Add HTML file links (excluding the index file itself)
          echo "<h2>HTML Files</h2>" >> index.html
          for file in *.html; do
            if [ "$file" != "index.html" ]; then
              echo "<a href='$file'>$file</a><br>" >> index.html
            fi
          done

        # Close the HTML 
          echo "</body></html>" >> index.html
