name: Generate and Deploy All_Reports.html

# Trigger this workflow when anything changes inside the combined-reports folder
on:
  push:
    paths:
      - 'combined-reports/**'

jobs:
  generate-report: # First job: create the HTML index
    runs-on: self-hosted # You can change to ubuntu-latest if you don't use a self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Checkout the code from the repo

      - name: Prepare Testapp directory and generate All_Reports.html
        run: |
        # Create output structure and copy reports into Testapp/
          mkdir -p Testapp/combined-reports
          cp -r combined-reports/* Testapp/combined-reports/

          # Navigate to the folder where HTML index will be generated
          cd Testapp/combined-reports

          # Start building the HTML index
          echo "<!DOCTYPE html>" > All_Reports.html
          echo "<html><head><title>All Reports</title></head><body>" >> All_Reports.html
          echo "<h1>All Reports</h1>" >> All_Reports.html

          # Add folder links (only folders inside combined-reports)
          echo "<h2>Folders</h2>" >> All_Reports.html
          for folder in */; do
            foldername=$(basename "$folder")
            echo "<a href='$folder'>$foldername/</a><br>" >> All_Reports.html
          done

          # Add HTML file links (excluding the index file itself)
          echo "<h2>HTML Files</h2>" >> All_Reports.html
          for file in *.html; do
            if [ "$file" != "All_Reports.html" ]; then
              echo "<a href='$file'>$file</a><br>" >> All_Reports.html
            fi
          done

          echo "</body></html>" >> All_Reports.html # Close the HTML

      - name: Upload Testapp directory as artifact
        uses: actions/upload-artifact@v3 # Save the Testapp folder for the next job
        with:
          name: testapp-artifact
          path: Testapp/

  deploy-to-gh-pages: # Second job: deploy the generated HTML to GitHub Pages
    runs-on: ubuntu-latest
    needs: generate-report # This job waits for the generate-report job to finish

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Testapp artifact from previous job
        uses: actions/download-artifact@v3
        with:
          name: testapp-artifact
          path: Testapp/

      - name: Deploy Testapp folder to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
