name: Generate index.html

on:
  push:
    paths:
      - 'gh-pages' # Trigger on any file changes

jobs:
  create-index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate index.html
      run: |
        # Create the index.html file
        echo "<!DOCTYPE html>" > index.html
        echo "<html>" >> index.html
        echo "<head>" >> index.html
        echo "<title>Combined Reports</title>" >> index.html
        echo "</head>" >> index.html
        echo "<body>" >> index.html
        echo "<h1>Links to Combined Reports</h1>" >> index.html

        # Add links to files in the combined-reports folder
        if [ -d "combined-reports" ]; then
          for file in combined-reports/*; do
            filename=$(basename "$file")
            echo "<a href='combined-reports/$filename'>$filename</a><br>" >> index.html
          done
        else
          echo "<p>No files found in the combined-reports folder.</p>" >> index.html
        fi

        echo "</body>" >> index.html
        echo "</html>" >> index.html

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add index.html
        git commit -m "Generate index.html with links to combined-reports"
        git push
