name: Playwright Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-playwright:
    name: Run Playwright Tests
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 23.1.0
        uses: actions/setup-node@v4
        with:
          node-version: 23.1.0

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright tests with HTML report
        run: |
          npx playwright test --reporter=html

      - name: Upload HTML report as artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: playwright-report

  deploy-pages:
    name: Deploy to GitHub Pages
    needs: run-playwright
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
