name: Playwright Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-playwright:
    name: Run Playwright Tests
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install the dependiencies
        run: |
          npx playwright install

      - name: Run Playwright tests with HTML report
        run: |
          npx playwright test 


